// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: laptop_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defined the input to RPC
// every RPC func accepts one req/mssg (no mult args)
// defines the req sent by the client
type CreateLaptopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Laptop        *Laptop                `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLaptopRequest) Reset() {
	*x = CreateLaptopRequest{}
	mi := &file_laptop_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLaptopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaptopRequest) ProtoMessage() {}

func (x *CreateLaptopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaptopRequest.ProtoReflect.Descriptor instead.
func (*CreateLaptopRequest) Descriptor() ([]byte, []int) {
	return file_laptop_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateLaptopRequest) GetLaptop() *Laptop {
	if x != nil {
		return x.Laptop
	}
	return nil
}

// Defines what the server wil return
// output of RPC server
type CreateLaptopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLaptopResponse) Reset() {
	*x = CreateLaptopResponse{}
	mi := &file_laptop_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLaptopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLaptopResponse) ProtoMessage() {}

func (x *CreateLaptopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLaptopResponse.ProtoReflect.Descriptor instead.
func (*CreateLaptopResponse) Descriptor() ([]byte, []int) {
	return file_laptop_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLaptopResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Define a req which can search for laptop with given specs
type SearchLaptopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLaptopRequest) Reset() {
	*x = SearchLaptopRequest{}
	mi := &file_laptop_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLaptopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLaptopRequest) ProtoMessage() {}

func (x *SearchLaptopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLaptopRequest.ProtoReflect.Descriptor instead.
func (*SearchLaptopRequest) Descriptor() ([]byte, []int) {
	return file_laptop_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchLaptopRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Define res which returns such laptop
type SearchLaptopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Laptop        *Laptop                `protobuf:"bytes,1,opt,name=laptop,proto3" json:"laptop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLaptopResponse) Reset() {
	*x = SearchLaptopResponse{}
	mi := &file_laptop_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLaptopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLaptopResponse) ProtoMessage() {}

func (x *SearchLaptopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLaptopResponse.ProtoReflect.Descriptor instead.
func (*SearchLaptopResponse) Descriptor() ([]byte, []int) {
	return file_laptop_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchLaptopResponse) GetLaptop() *Laptop {
	if x != nil {
		return x.Laptop
	}
	return nil
}

type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*UploadImageRequest_Info
	//	*UploadImageRequest_ChunkData
	Data          isUploadImageRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_laptop_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_laptop_service_proto_rawDescGZIP(), []int{4}
}

func (x *UploadImageRequest) GetData() isUploadImageRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageRequest) GetInfo() *ImageInfo {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadImageRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Data.(*UploadImageRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadImageRequest_Data interface {
	isUploadImageRequest_Data()
}

type UploadImageRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadImageRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadImageRequest_Info) isUploadImageRequest_Data() {}

func (*UploadImageRequest_ChunkData) isUploadImageRequest_Data() {}

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LaptopId      string                 `protobuf:"bytes,1,opt,name=laptop_id,json=laptopId,proto3" json:"laptop_id,omitempty"`
	ImageType     string                 `protobuf:"bytes,2,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_laptop_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_laptop_service_proto_rawDescGZIP(), []int{5}
}

func (x *ImageInfo) GetLaptopId() string {
	if x != nil {
		return x.LaptopId
	}
	return ""
}

func (x *ImageInfo) GetImageType() string {
	if x != nil {
		return x.ImageType
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_laptop_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_laptop_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_laptop_service_proto_rawDescGZIP(), []int{6}
}

func (x *UploadImageResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadImageResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_laptop_service_proto protoreflect.FileDescriptor

const file_laptop_service_proto_rawDesc = "" +
	"\n" +
	"\x14laptop_service.proto\x12\x05proto\x1a\x14screen_message.proto\x1a\x17processor_message.proto\x1a\x14memory_message.proto\x1a\x15storage_message.proto\x1a\x16keyboard_message.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14laptop_message.proto\x1a\x14filter_message.proto\"<\n" +
	"\x13CreateLaptopRequest\x12%\n" +
	"\x06laptop\x18\x01 \x01(\v2\r.proto.LaptopR\x06laptop\"&\n" +
	"\x14CreateLaptopResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x13SearchLaptopRequest\x12%\n" +
	"\x06filter\x18\x01 \x01(\v2\r.proto.FilterR\x06filter\"=\n" +
	"\x14SearchLaptopResponse\x12%\n" +
	"\x06laptop\x18\x01 \x01(\v2\r.proto.LaptopR\x06laptop\"e\n" +
	"\x12UploadImageRequest\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x10.proto.ImageInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x06\n" +
	"\x04data\"G\n" +
	"\tImageInfo\x12\x1b\n" +
	"\tlaptop_id\x18\x01 \x01(\tR\blaptopId\x12\x1d\n" +
	"\n" +
	"image_type\x18\x02 \x01(\tR\timageType\"9\n" +
	"\x13UploadImageResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size2\xf1\x01\n" +
	"\rLaptopService\x12I\n" +
	"\fCreateLaptop\x12\x1a.proto.CreateLaptopRequest\x1a\x1b.proto.CreateLaptopResponse\"\x00\x12K\n" +
	"\fSearchLaptop\x12\x1a.proto.SearchLaptopRequest\x1a\x1b.proto.SearchLaptopResponse\"\x000\x01\x12H\n" +
	"\vUploadImage\x12\x19.proto.UploadImageRequest\x1a\x1a.proto.UploadImageResponse\"\x00(\x01B)Z'github.com/shriyash/grpc_practice/pb;pbb\x06proto3"

var (
	file_laptop_service_proto_rawDescOnce sync.Once
	file_laptop_service_proto_rawDescData []byte
)

func file_laptop_service_proto_rawDescGZIP() []byte {
	file_laptop_service_proto_rawDescOnce.Do(func() {
		file_laptop_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_laptop_service_proto_rawDesc), len(file_laptop_service_proto_rawDesc)))
	})
	return file_laptop_service_proto_rawDescData
}

var file_laptop_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_laptop_service_proto_goTypes = []any{
	(*CreateLaptopRequest)(nil),  // 0: proto.CreateLaptopRequest
	(*CreateLaptopResponse)(nil), // 1: proto.CreateLaptopResponse
	(*SearchLaptopRequest)(nil),  // 2: proto.SearchLaptopRequest
	(*SearchLaptopResponse)(nil), // 3: proto.SearchLaptopResponse
	(*UploadImageRequest)(nil),   // 4: proto.UploadImageRequest
	(*ImageInfo)(nil),            // 5: proto.ImageInfo
	(*UploadImageResponse)(nil),  // 6: proto.UploadImageResponse
	(*Laptop)(nil),               // 7: proto.Laptop
	(*Filter)(nil),               // 8: proto.Filter
}
var file_laptop_service_proto_depIdxs = []int32{
	7, // 0: proto.CreateLaptopRequest.laptop:type_name -> proto.Laptop
	8, // 1: proto.SearchLaptopRequest.filter:type_name -> proto.Filter
	7, // 2: proto.SearchLaptopResponse.laptop:type_name -> proto.Laptop
	5, // 3: proto.UploadImageRequest.info:type_name -> proto.ImageInfo
	0, // 4: proto.LaptopService.CreateLaptop:input_type -> proto.CreateLaptopRequest
	2, // 5: proto.LaptopService.SearchLaptop:input_type -> proto.SearchLaptopRequest
	4, // 6: proto.LaptopService.UploadImage:input_type -> proto.UploadImageRequest
	1, // 7: proto.LaptopService.CreateLaptop:output_type -> proto.CreateLaptopResponse
	3, // 8: proto.LaptopService.SearchLaptop:output_type -> proto.SearchLaptopResponse
	6, // 9: proto.LaptopService.UploadImage:output_type -> proto.UploadImageResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_laptop_service_proto_init() }
func file_laptop_service_proto_init() {
	if File_laptop_service_proto != nil {
		return
	}
	file_screen_message_proto_init()
	file_processor_message_proto_init()
	file_memory_message_proto_init()
	file_storage_message_proto_init()
	file_keyboard_message_proto_init()
	file_laptop_message_proto_init()
	file_filter_message_proto_init()
	file_laptop_service_proto_msgTypes[4].OneofWrappers = []any{
		(*UploadImageRequest_Info)(nil),
		(*UploadImageRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_laptop_service_proto_rawDesc), len(file_laptop_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_laptop_service_proto_goTypes,
		DependencyIndexes: file_laptop_service_proto_depIdxs,
		MessageInfos:      file_laptop_service_proto_msgTypes,
	}.Build()
	File_laptop_service_proto = out.File
	file_laptop_service_proto_goTypes = nil
	file_laptop_service_proto_depIdxs = nil
}
